!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 3280.0
  P2: 4000.0
  correlation_window_size: 5
  disp12MaxDiff: 128
  disparity_range: 144
  fullDP: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 3280.0
      P2: 4000.0
      correlation_window_size: 5
      disp12MaxDiff: 128
      disparity_range: 144
      fullDP: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: 3
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 31
      prefilter_size: 21
      speckle_range: 31
      speckle_size: 0
      state: true
      stereo_algorithm: 1
      texture_threshold: 0
      type: ''
      uniqueness_ratio: 0.0
    state: []
  min_disparity: 3
  prefilter_cap: 31
  prefilter_size: 21
  speckle_range: 31
  speckle_size: 0
  stereo_algorithm: 1
  texture_threshold: 0
  uniqueness_ratio: 0.0
state: []
